<?php

namespace Athphane\FilamentEditorjs\Support;

class LanguageRegistry
{
    protected array $languages = [
        'abap' => 'ABAP',
        'actionscript-3' => 'ActionScript 3',
        'ada' => 'Ada',
        'apache' => 'Apache',
        'apex' => 'Apex',
        'apl' => 'APL',
        'applescript' => 'AppleScript',
        'ara' => 'Arabic',
        'asm' => 'Assembly',
        'astro' => 'Astro',
        'awk' => 'Awk',
        'ballerina' => 'Ballerina',
        'bash' => 'Bash',
        'batch' => 'Batch',
        'bibtex' => 'BibTeX',
        'bicep' => 'Bicep',
        'blade' => 'Blade',
        'c' => 'C',
        'c-algol68' => 'C (Algol68)',
        'c++' => 'C++',
        'c#-dev' => 'C# (Dev)',
        'c#' => 'C#',
        'caddyfile' => 'Caddyfile',
        'cake' => 'Cake',
        'carp' => 'Carp',
        'clarity' => 'Clarity',
        'clojure' => 'Clojure',
        'cmake' => 'CMake',
        'cobol' => 'COBOL',
        'codeql' => 'CodeQL',
        'coffeescript' => 'CoffeeScript',
        'common-lisp' => 'Common Lisp',
        'coq' => 'Coq',
        'cpp' => 'C++',
        'crystal' => 'Crystal',
        'csharp' => 'C#',
        'css' => 'CSS',
        'cue' => 'CUE',
        'cypher' => 'Cypher',
        'd' => 'D',
        'dart' => 'Dart',
        'data-weave' => 'DataWeave',
        'dax' => 'DAX',
        'dhall' => 'Dhall',
        'django' => 'Django',
        'dockerfile' => 'Dockerfile',
        'dot' => 'DOT (Graphviz)',
        'dream-maker' => 'Dream Maker',
        'dylan' => 'Dylan',
        'ebnf' => 'EBNF',
        'ecl' => 'ECL',
        'edge' => 'Edge',
        'editorconfig' => 'EditorConfig',
        'eiffel' => 'Eiffel',
        'ejs' => 'EJS',
        'elisp' => 'Emacs Lisp',
        'elixir' => 'Elixir',
        'elm' => 'Elm',
        'emacs-lisp' => 'Emacs Lisp',
        'erlang' => 'Erlang',
        'f#' => 'F#',
        'factor' => 'Factor',
        'fennel' => 'Fennel',
        'fish' => 'Fish',
        'forth' => 'Forth',
        'fortran' => 'Fortran',
        'fsharp' => 'F#',
        'fsl' => 'FSL',
        'ftl' => 'FreeMarker',
        'gap' => 'GAP',
        'gcode' => 'G-code',
        'gdscript' => 'GDScript',
        'gerber' => 'Gerber',
        'gherkin' => 'Gherkin',
        'git-commit' => 'Git Commit',
        'git-rebase' => 'Git Rebase',
        'glsl' => 'GLSL',
        'gnuplot' => 'Gnuplot',
        'go' => 'Go',
        'godot' => 'GDScript',
        'gradle' => 'Gradle',
        'graphql' => 'GraphQL',
        'groovy' => 'Groovy',
        'hack' => 'Hack',
        'haml' => 'HAML',
        'handlebars' => 'Handlebars',
        'haskell' => 'Haskell',
        'haxe' => 'Haxe',
        'hcl' => 'HCL',
        'hlsl' => 'HLSL',
        'hocon' => 'HOCON',
        'html' => 'HTML',
        'http' => 'HTTP',
        'hunspell' => 'Hunspell',
        'hy' => 'Hy',
        'imba' => 'Imba',
        'inform-7' => 'Inform 7',
        'ini' => 'INI',
        'ink' => 'Ink',
        'inno' => 'Inno Setup',
        'isabelle' => 'Isabelle',
        'j' => 'J',
        'java' => 'Java',
        'javascript' => 'JavaScript',
        'jinja-html' => 'Jinja HTML',
        'jison' => 'Jison',
        'jisonlex' => 'Jison Lex',
        'json' => 'JSON',
        'json5' => 'JSON5',
        'jsonc' => 'JSONC',
        'jsonnet' => 'Jsonnet',
        'jssm' => 'JSSM',
        'jsx' => 'JSX',
        'julia' => 'Julia',
        'kotlin' => 'Kotlin',
        'kusto' => 'Kusto',
        'latex' => 'LaTeX',
        'latte' => 'Latte',
        'lean' => 'Lean',
        'less' => 'Less',
        'liquid' => 'Liquid',
        'lisp' => 'Lisp',
        'llvm' => 'LLVM',
        'log' => 'Log',
        'lolcode' => 'LOLCODE',
        'lua' => 'Lua',
        'make' => 'Makefile',
        'markdown' => 'Markdown',
        'marko' => 'Marko',
        'matlab' => 'MATLAB',
        'mdx' => 'MDX',
        'mermaid' => 'Mermaid',
        'meson' => 'Meson',
        'miller' => 'Miller',
        'mint' => 'Mint',
        'mlir' => 'MLIR',
        'mojo' => 'Mojo',
        'monkey' => 'Monkey',
        'moonscript' => 'MoonScript',
        'n1ql' => 'N1QL',
        'nasm' => 'NASM',
        'neon' => 'NEON',
        'nginx' => 'Nginx',
        'nim' => 'Nim',
        'nix' => 'Nix',
        'nsis' => 'NSIS',
        'nu' => 'Nu',
        'numpy' => 'NumPy',
        'nunjucks' => 'Nunjucks',
        'objective-c' => 'Objective-C',
        'objective-cpp' => 'Objective-C++',
        'ocaml' => 'OCaml',
        'odin' => 'Odin',
        'openscad' => 'OpenSCAD',
        'org' => 'Org',
        'pascal' => 'Pascal',
        'pascaligo' => 'Pascaligo',
        'pcre2' => 'PCRE2',
        'perl' => 'Perl',
        'php' => 'PHP',
        'plsql' => 'PL/SQL',
        'plaintext' => 'Plain Text',
        'pony' => 'Pony',
        'postcss' => 'PostCSS',
        'powershell' => 'PowerShell',
        'prisma' => 'Prisma',
        'prolog' => 'Prolog',
        'promql' => 'PromQL',
        'properties' => 'Properties',
        'proto' => 'Protocol Buffers',
        'prql' => 'PRQL',
        'pug' => 'Pug',
        'puppet' => 'Puppet',
        'purescript' => 'PureScript',
        'python' => 'Python',
        'q' => 'Q',
        'qml' => 'QML',
        'qsharp' => 'Q#',
        'r' => 'R',
        'racket' => 'Racket',
        'razor' => 'Razor',
        'rbs' => 'RBS',
        'rebol' => 'Rebol',
        'rego' => 'Rego',
        'renpy' => 'Ren\'Py',
        'rescript' => 'ReScript',
        'riscv' => 'RISC-V',
        'rmarkdown' => 'RMarkdown',
        'robot' => 'Robot Framework',
        'roff' => 'Roff',
        'ruby' => 'Ruby',
        'rust' => 'Rust',
        's' => 'S',
        'sas' => 'SAS',
        'sass' => 'Sass',
        'scala' => 'Scala',
        'scheme' => 'Scheme',
        'scss' => 'SCSS',
        'shaderlab' => 'ShaderLab',
        'shell' => 'Shell',
        'shellscript' => 'ShellScript',
        'smali' => 'Smali',
        'smalltalk' => 'Smalltalk',
        'solidity' => 'Solidity',
        'sophia' => 'Sophia',
        'sparql' => 'SPARQL',
        'splunk-spl' => 'Splunk SPL',
        'sqf' => 'SQF',
        'sql' => 'SQL',
        'squirrel' => 'Squirrel',
        'stan' => 'Stan',
        'stata' => 'Stata',
        'stylus' => 'Stylus',
        'subunit' => 'SubUnit',
        'svelte' => 'Svelte',
        'swift' => 'Swift',
        'system-verilog' => 'SystemVerilog',
        't32' => 'T32',
        'tap' => 'TAP',
        'tcl' => 'Tcl',
        'templ' => 'Templ',
        'terraform' => 'Terraform',
        'tex' => 'TeX',
        'textmate' => 'TextMate',
        'thrift' => 'Thrift',
        'toml' => 'TOML',
        'ts' => 'TypeScript',
        'tsx' => 'TSX',
        'ttcn' => 'TTCN',
        'turtle' => 'Turtle',
        'twig' => 'Twig',
        'typescript' => 'TypeScript',
        'unison' => 'Unison',
        'unified' => 'Unified',
        'v' => 'V',
        'vala' => 'Vala',
        'vb' => 'VB',
        'verilog' => 'Verilog',
        'vhdl' => 'VHDL',
        'vim' => 'Vim Script',
        'viml' => 'VimL',
        'visual-basic' => 'Visual Basic',
        'vlang' => 'V',
        'vue' => 'Vue',
        'wasm' => 'WebAssembly',
        'wdl' => 'WDL',
        'wgsl' => 'WGSL',
        'wolfram' => 'Wolfram',
        'wren' => 'Wren',
        'xml' => 'XML',
        'xquery' => 'XQuery',
        'yaml' => 'YAML',
        'zenscript' => 'ZenScript',
        'zephir' => 'Zephir',
        'zig' => 'Zig',
    ];

    protected array $popularLanguages = [
        'javascript' => 'JavaScript',
        'typescript' => 'TypeScript',
        'python' => 'Python',
        'java' => 'Java',
        'php' => 'PHP',
        'go' => 'Go',
        'rust' => 'Rust',
        'ruby' => 'Ruby',
        'c#' => 'C#',
        'c++' => 'C++',
        'swift' => 'Swift',
        'kotlin' => 'Kotlin',
        'sql' => 'SQL',
        'html' => 'HTML',
        'css' => 'CSS',
        'json' => 'JSON',
        'yaml' => 'YAML',
        'bash' => 'Bash',
        'shell' => 'Shell',
    ];

    public function getLanguages(): array
    {
        return $this->languages;
    }

    public function getPopularLanguages(): array
    {
        return $this->popularLanguages;
    }

    public function getLanguageName(string $code): ?string
    {
        return $this->languages[$code] ?? null;
    }

    public function getLanguagesGroupedByCategory(): array
    {
        $popular = $this->popularLanguages;

        $webDevelopment = [
            'javascript' => 'JavaScript',
            'typescript' => 'TypeScript',
            'html' => 'HTML',
            'css' => 'CSS',
            'scss' => 'SCSS',
            'sass' => 'Sass',
            'less' => 'Less',
            'php' => 'PHP',
            'vue' => 'Vue',
            'svelte' => 'Svelte',
        ];

        $mobileDesktop = [
            'swift' => 'Swift',
            'kotlin' => 'Kotlin',
            'c#' => 'C#',
            'java' => 'Java',
        ];

        $systemsPerformance = [
            'c' => 'C',
            'c++' => 'C++',
            'rust' => 'Rust',
            'go' => 'Go',
            'assembly' => 'Assembly',
        ];

        $dataScripting = [
            'python' => 'Python',
            'r' => 'R',
            'ruby' => 'Ruby',
            'perl' => 'Perl',
            'bash' => 'Bash',
            'shell' => 'Shell',
            'powershell' => 'PowerShell',
        ];

        $dataFormats = [
            'json' => 'JSON',
            'xml' => 'XML',
            'yaml' => 'YAML',
            'toml' => 'TOML',
            'ini' => 'INI',
        ];

        $databases = [
            'sql' => 'SQL',
            'plsql' => 'PL/SQL',
            'sparql' => 'SPARQL',
        ];

        $usedLanguages = array_merge(
            $popular,
            $webDevelopment,
            $mobileDesktop,
            $systemsPerformance,
            $dataScripting,
            $dataFormats,
            $databases
        );

        $categories = [
            'Popular' => $popular,
            'Web Development' => $webDevelopment,
            'Mobile & Desktop' => $mobileDesktop,
            'Systems & Performance' => $systemsPerformance,
            'Data & Scripting' => $dataScripting,
            'Data Formats' => $dataFormats,
            'Databases' => $databases,
            'Other' => array_diff_key($this->languages, $usedLanguages),
        ];

        return $categories;
    }

    public function searchLanguages(string $query): array
    {
        $query = strtolower($query);
        $results = [];

        foreach ($this->languages as $code => $name) {
            if (str_contains(strtolower($name), $query) || str_contains(strtolower($code), $query)) {
                $results[$code] = $name;
            }
        }

        return $results;
    }
}
